#!/bin/bash


door[1]=0
door[2]=0
door[3]=0
ri=0

winner=$(( 1 + $RANDOM % 3 ))

door[$winner]=1


echo enter a number to pick door 1, 2 or 3

read firstpick

echo I will now show you what is behind one of the doors
echo please hit the Enter key when you are ready for me to reveal this to you

read ready

#if [ $winner -eq $firstpick ]; then

#  echo firstpick won, this is just a stub message though ;

#fi

for i in `seq 1 3` ; do 
#	echo i is $i
	if [ $winner -ne $i ]; then
		if [ $firstpick -ne $i ]; then
			remainder[$ri]=$i
#			echo remainder sub ri is ${remainder[$ri]} and ri is $ri
			ri=$(($ri+1))
#			echo and ri is now $ri
		fi

	fi
done

#echo remainder count is ${#remainder}


if [ $ri -gt 1 ]; then
	reveal=$(( $RANDOM % 2 ))
#	echo reveal is $reveal
#	echo There is a goat behind door ${remainder[$reveal]}
else
	reveal=0
fi

	echo There is a goat behind this door: ${remainder[$reveal]}

#echo winner is $winner
#echo firstpick is $firstpick

for i in `seq 1 3` ; do 
#	echo i is $i
	if [ ${remainder[$reveal]} -ne $i ]; then
		if [ $firstpick -ne $i ]; then
			echo "Do you want to switch to door $i (y/n)"
			read switchdoor
			if [ $switchdoor = "y" ]; then
				pick=$i
			elif [ $switchdoor = "n" ]; then
				pick=$firstpick
			else
				echo Sorry, I needed a y or no answer there, going with your first pick
				exit
			fi
		fi

	fi
done

if [ $pick -eq $winner ]; then
	echo You won! The prize was behind door $winner and you picked door $pick
else
	echo Sorry! The prize was behind door $winner but you picked door $pick
fi

